### ISSUE TITLE
Bug: next date off by one day

### ISSUE THREAD

**Issue by debpaul** [SpeciesFileGroup/speciesfilegroup.github.io#23]
@jlpereira the dates for "next date" are off by one day.

![image](https://user-images.githubusercontent.com/2990155/151634882-af1709c3-26e4-477a-8f1a-f7072e827580.png)
![image](https://user-images.githubusercontent.com/2990155/151634955-de27c6d7-a155-4fcf-a050-96ab0c669414.png)

**Comment by jlpereira** [comment]
Yah, saw it. Already pushed a fix for it
